/**
 * Curated model descriptions for dropdown/list UI.
 * Source: https://developers.openai.com/api/docs/models (All models section).
 * No API provides these; the list API only returns id, created, object, owned_by.
 */

export const OPENAI_MODEL_DESCRIPTIONS: Record<string, string> = {
  'gpt-5.2': 'The best model for coding and agentic tasks across industries.',
  'gpt-5-mini': 'A faster, cost-efficient version of GPT-5 for well-defined tasks.',
  'gpt-5-nano': 'Fastest, most cost-efficient version of GPT-5.',
  'gpt-5.2-pro': 'Version of GPT-5.2 that produces smarter and more precise responses.',
  'gpt-5-pro': 'Version of GPT-5 that produces smarter and more precise responses.',
  'gpt-5.1': 'The best model for coding and agentic tasks with configurable reasoning effort.',
  'gpt-5': 'Previous intelligent reasoning model for coding and agentic tasks with configurable reasoning effort.',
  'gpt-5.2-codex': 'Most intelligent coding model optimized for long-horizon, agentic coding tasks.',
  'gpt-5.1-codex': 'A version of GPT-5.1 optimized for agentic coding in Codex.',
  'gpt-5.1-codex-max': 'A version of GPT-5.1-codex optimized for long running tasks.',
  'gpt-5-codex': 'A version of GPT-5 optimized for agentic coding in Codex.',
  'gpt-5.1-codex-mini': 'Smaller, more cost-effective, less-capable version of GPT-5.1-Codex.',
  'gpt-4.1': 'Smartest non-reasoning model.',
  'gpt-4.1-mini': 'Smaller, faster version of GPT-4.1.',
  'gpt-4.1-nano': 'Fastest, most cost-efficient version of GPT-4.1.',
  'o3': 'Reasoning model for complex tasks, succeeded by GPT-5.',
  'o3-mini': 'A small model alternative to o3.',
  'o4-mini': 'Fast, cost-efficient reasoning model, succeeded by GPT-5 mini.',
  'o1': 'Previous full o-series reasoning model.',
  'o1-pro': 'Version of o1 with more compute for better responses.',
  'o1-mini': 'A small model alternative to o1.',
  'gpt-4o': 'Fast, intelligent, flexible GPT model.',
  'gpt-4o-mini': 'Fast, affordable small model for focused tasks.',
  'gpt-4o-audio-preview': 'GPT-4o models capable of audio inputs and outputs.',
  'gpt-4o-mini-audio-preview': 'Smaller model capable of audio inputs and outputs.',
  'gpt-4o-mini-realtime-preview': 'Smaller realtime model for text and audio inputs and outputs.',
  'gpt-4o-realtime-preview': 'Model capable of realtime text and audio inputs and outputs.',
  'gpt-4o-mini-transcribe': 'Speech-to-text model powered by GPT-4o mini.',
  'gpt-4o-mini-tts': 'Text-to-speech model powered by GPT-4o mini.',
  'gpt-4o-transcribe': 'Speech-to-text model powered by GPT-4o.',
  'gpt-4o-transcribe-diarize': 'Transcription model that identifies who is speaking when.',
  'gpt-4-turbo': 'An older high-intelligence GPT model.',
  'gpt-4': 'An older high-intelligence GPT model.',
  'gpt-3.5-turbo': 'Legacy GPT model for cheaper chat and non-chat tasks.',
  'sora-2': 'Flagship video generation with synced audio.',
  'sora-2-pro': 'Most advanced synced-audio video generation.',
  'gpt-image-1.5': 'State-of-the-art image generation model.',
  'gpt-image-1': 'Our previous image generation model.',
  'gpt-image-1-mini': 'A cost-efficient version of GPT Image 1.',
  'chatgpt-image-latest': 'Image model used in ChatGPT.',
  'dall-e-2': 'Our first image generation model.',
  'dall-e-3': 'Previous generation image generation model.',
  'gpt-realtime': 'Model capable of realtime text and audio inputs and outputs.',
  'gpt-realtime-mini': 'A cost-efficient version of GPT Realtime.',
  'gpt-audio': 'For audio inputs and outputs with Chat Completions API.',
  'gpt-audio-mini': 'A cost-efficient version of GPT Audio.',
  'whisper-1': 'General-purpose speech recognition model.',
  'tts-1': 'Text-to-speech model optimized for speed.',
  'tts-1-hd': 'Text-to-speech model optimized for quality.',
  'text-embedding-3-large': 'Most capable embedding model.',
  'text-embedding-3-small': 'Small embedding model.',
  'text-embedding-ada-002': 'Older embedding model.',
  'omni-moderation-latest': 'Identify potentially harmful content in text and images.',
  'babbage-002': 'Replacement for the GPT-3 ada and babbage base models.',
  'davinci-002': 'Replacement for the GPT-3 curie and davinci base models.',
  'gpt-4o-mini-search-preview': 'Fast, affordable small model for web search.',
  'gpt-4o-search-preview': 'GPT model for web search in Chat Completions.',
}

/** Suggested model prefix per provider (powerful, price-sensitive). First match in availableModels is used. */
export const SUGGESTED_MODEL_PREFIX: Record<string, string> = {
  openai: 'gpt-5-mini',
  anthropic: 'claude-3-5-haiku',
}
